name: Permissions
main: com.github.neapovil.permissions.Permissions
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/permissions
depend:
  - CommandAPI
permissions:
  permissions.command:
    default: op
